### PR TITLE
Remove fab

### PR DESCRIPTION
**Pull request by smichel17**
All functionality changes are in the first commit. Feel free to take just it if you don't like the style changes.

### CODE REVIEW

**Comment by smichel17** [comment]
I didn't do any extensive testing, but it seems to work on an emulated Nexus 5X, API 24.

**Comment by tibbi** [comment]
looks nice, thanks :) The style changes are ok too, I didnt realise there is no break or return needed inbetween cases. Its fairly new to me too.

**Comment by smichel17** [comment]
Yeah. I've only been doing android for a couple months myself (mostly in kotlin). Every so often I still stumble upon a kotlin feature I didn't know about.

**Comment by smichel17** [comment]
Notably, I stumbled across a couple new things when I finally got around to doing the [Kotlin Koans](https://kotlinlang.org/docs/tutorials/koans.html).

**Pull request merged**
