### PR TITLE
Automatic backups

### LINKED ISSUE #364: [feature request] automatic export of notes/persistent files
Right now, notes are not represented in the file system (at least not in the user space?) and it'd be very handy if every note were a file (txt or markdown for example) in order to be able to sync them across devices.

### PR DESCRIPTION
**Pull request by Merkost**
Implemented the same way like in simple-contacts and simple-calendar

Close #364

### CODE REVIEW

**Comment by Merkost** [comment]
Better to extract DateTimePatternInfoDialog to simple-commons, as the same dialog is used in calendar, contacts and notes separately now?

**Comment by tibbi** [comment]
we should not show an "Exporting successful" toast message at backup

**Comment by tibbi** [comment]
we can move it later, updating commons is difficult now because of some viewbinding changes and target SDK has to be changed to 34 too

**Comment by tibbi** [comment]
ok thanks, guess that will do it

**Pull request merged**
