### PR TITLE
Added the ability to display notes as a list instead of in a view pager

### PR DESCRIPTION
**Pull request by olfek**

### CODE REVIEW

**Comment by olfek** [comment]
I have tested everything, and it works as expected, but I still recommend that you test everything thoroughly before merging because the nature of this code is high risk and has the potential to break things.

**Comment by tibbi** [comment]
oh my gosh, this is a lot of code with terrible code style and formatting. Please at least read some other files before adding any own code.

**Comment by olfek** [comment]
I agree that the code isn't great, but this is the only way the feature
could be added because of the limitations of the existing code.

Also, this is my first time with Kotlin, I am primarily a java developer.

**Comment by olfek** [comment]
What specifically would you like me to change about the styling and formatting?

**Comment by olfek** [comment]
Unrelated, but I just wanted to mention that the MainActivity file is too long, it should be broken up.

**Comment by olfek** [comment]
Why is it that the 'LAYOUT' label in settings is not orange like the rest of the labels?, It has exactly the same XML attributes apart from ID?

**Comment by olfek** [comment]
Demo of feature in action:
untitled

**Comment by tibbi** [comment]
not sure what you mean with the orange label. Anyway I honestly dont see much sense in that feature anymore, you were going to do it in december :/ Since then you can already show a list of available notes at startup or just press "Open note" to see a list of available notes. This doesnt make the app any more simple or useful.

**Comment by olfek** [comment]
Firstly, I think it would improve performance for people that have large notes, because the view pager basically has them all open at once, where as this list layout only opens the note when it is clicked.

Secondly, suppose someone is storing sensitive information in their notes, I.e. passwords or social security number, when they open the app, the note is immediately shown which others looking over their shoulder could take advantage of. With the list implementation, they can think carefully before opening the sensitive note. With the view pager, it may be the case that they do not even wish to view the sensitive note, they wish to see another note, but due to the nature of the view pager, they must first swipe past the sensitive note to get to the note they wish to see.

Besides, merging this code will have no effect on users, they will only see the alternative layout if they enable it in settings.

If you do decide to merge this, I recommend that some time in the future, you refactor all the code to make list view the default, view pager should be the alternative option.

**Comment by tibbi** [comment]
I will see how will I handle password protected notes, they wont come anytime soon anyway. Ill close this solution as it is way too complicated, thanks though.

**Pull request closed without merging**
