### PR TITLE
Avoid crash when clicking with text selected and links enabled. Fixes #93.

### LINKED ISSUE #93: Selecting text and clicking anywhere leads to crash
Make links active option must be enabled to make this reproduce.

### PR DESCRIPTION
**Pull request by trubitsyn**

### CODE REVIEW

**Comment by trubitsyn** [comment]
In the current implementation swiping to another note with text selected disables links in the first note. Working on that.

**Comment by trubitsyn** [comment]
Now that works fine. I don't like that global variable, but it seems there's no other way to fix that.

**Comment by tibbi** [comment]
Thanks, Ive updated the code a bit, please use "apply" instead of "with", thats used all over the code.

**Comment by trubitsyn** [comment]
OK, I'll follow your style.

**Pull request merged**
