### PR TITLE
Use Stetho in debug builds only

### PR DESCRIPTION
**Pull request by trubitsyn**
Currently it runs in release builds (just downloaded from Google Play) and wastes resources.

### CODE REVIEW

**Comment by tibbi** [comment]
Hey, thanks for the idea. Ive added a much simpler way for initializing it only in debug mode.

**Comment by trubitsyn** [comment]
Maybe to set debugCompile for Stetho in build.gradle? It would save some space then.

**Comment by tibbi** [comment]
its giving error at compiling Release then, as the class "Stetho" is not known at all. The whole app is less than 5 MB on almost all devices, I dont want to spend time optimizing that.

**Comment by trubitsyn** [comment]
I thought Gradle could find out that it is used only in debug. Whatever.

**Pull request closed without merging**
