### PR TITLE
Added new checklist items at the top (#583)

### LINKED ISSUE #583: Request : Setting to add items to top of checklists
New items are automatically added to the bottom of lists. I never want them there! :) I find myself constantly adding to the end and then manually moving them all the way to the top / near the top. Perhaps not everyone wants this so maybe you can put it in Settings? "Add items to the top"

Thanks

### PR DESCRIPTION
**Pull request by Aga-C**
Closes #583

I've reverted this feature. It works when sorting is set to Custom.

### CODE REVIEW

**Comment by tibbi** [comment]
lets move the checkbox into the dialog with adding new items itself for quick toggle

**Comment by tibbi** [comment]
also make sure it works well with Custom sorting

**Comment by Aga-C** [comment]
> lets move the checkbox into the dialog with adding new items itself for quick toggle

Maybe we should display it only when sorting is set to Custom? Because otherwise, it will get sorted instead being added to top or bottom.

**Comment by tibbi** [comment]
well, adding to the top makes sense only at custom sorting indeed. So ye, show the checkbox only at custom sorting

**Comment by Aga-C** [comment]
Does this look ok? And I've a doubt about the string, maybe it should be shortened as now it's not in the settings.
image

**Comment by tibbi** [comment]
looks good, Ill test it later. Added a new string add_to_the_top, you can use that. It will at least get translated while I get to it.

**Comment by tibbi** [comment]
looks good, thanks

**Pull request merged**
