### PR TITLE
For #498: Fix toolbar button order

### PR DESCRIPTION
**Pull request by bigConifer**
Provide consistency between note mode and checklist mode.

### CODE REVIEW

**Comment by tibbi** [comment]
different notes have different options, they cannot be the same. And you cannot have 5 menu items with app:showAsAction "Always", that will make the app title become invisible in some cases

**Comment by bigConifer** [comment]
@tibbi Let's take a look. I'll help you to understand.

> options cannot be the same

This PR is NOT about making the options the same but about making them CONSISTENT.
Finally this will fix the issue, that the "+" option in toolbar is shown only for checklists. 
It might be useful to read the referenced issue #498.

> you cannot have 5 menu items with app:showAsAction "Always"

Yes, you can! For text notes there are already 5 items with "always". This would also be the case for checklists after this commit.

<p>
  
   
</p>
Current state: 
During editing, the app title is already invisible for some languages or on small devices.

**Comment by bigConifer** [comment]
I will be happy to answer further questions.

It is better to review community commits appreciatively and ask questions than to close immediately.

**Comment by tibbi** [comment]
that is terrible UX to force that many icons shown

**Comment by bigConifer** [comment]
> terrible UX to force that many icons shown

No offence, but your ranting against your own UX!
The screenshots above are taken in the current release 6.12.0 Pro without any changes.

Additionally this PR will not change the number of items shown. The "+" option will move into the dropdown menu when there is no room for it. This is already the case for Text notes and would be applied to Checklists as well (see #498). So the UX will become more consistent and definitely not more cluttered.

**Comment by bigConifer** [comment]
Finally, it seems like the options "save_note", "undo" and "redo" are never shown for Checklists. Therefore the number of items shown will stay 2.

So it is actually groundless to talk about 5 menu items.

**Pull request closed without merging**
