### PR TITLE
Implement appending text received from external application

### PR DESCRIPTION
**Pull request by trubitsyn**
Works as of now. Code needs some polishing, so it's WIP. I haven't decided what's the right name for a selection dialog yet, so I haven't created string resources for other languages.

### CODE REVIEW

**Comment by tibbi** [comment]
well no need to create pull requests if its not done yet

**Comment by smichel17** [comment]
It allows for a discussion, if any is needed.

**Comment by trubitsyn** [comment]
Ready to merge.

**Comment by trubitsyn** [comment]
Forgot to update language files.

**Comment by tibbi** [comment]
try implementing it as 1 dialog with the simple RadioGroupDialog, where the first item will be "Create a new note". You can then remove the "update_note" string too.

**Comment by trubitsyn** [comment]
What if a note "Create a new note" exists? It would look strange.

**Comment by trubitsyn** [comment]
And if there's no "update_note" string, how would user know the text is going to be appended to note?

**Comment by trubitsyn** [comment]
If somebody is wondering how it looks currently

screenshot_20170618-183452_1

**Comment by tibbi** [comment]
no need to care about notes called "Create a new note", that wont happen. Use a dialog title "Add text to", then list the existing notes starting with "Create a new note"

**Comment by tibbi** [comment]
Ive just tweaked the RadioGroupDialog to allow setting an optional title id too, its in commons 2.21.4

**Comment by trubitsyn** [comment]
Oh, I didn't see your message. One minute...

**Comment by trubitsyn** [comment]
@tibbi I can't realize how to get clicked id with RadioGroupDialog. Could you guide me?

**Comment by tibbi** [comment]
you cannot get the clicked id directly, just its final value. Fill it with RadioItem(0, getString(R.string.create_new_note)), RadioItem(1, General Note), RadioItem(2, Another note) and at the callback you will get either 0, 1 or 2. It supports any return type, just cast it to int.

**Comment by trubitsyn** [comment]
With RadioGroupDialog it's impossible to click on an already checked item.

**Comment by trubitsyn** [comment]
Look, it should be alright.

**Comment by tibbi** [comment]
remove the ImportDataDialog class totally, its not needed. Just handle the whole thing in a function at MainActivity. Also in the future avoid passing 2 callbacks to dialogs, its really hard to understand.

Also replace "fragments[position]?.getNotesView()?.setText("${getCurrentNoteViewText(position)}$text")" with .appendText(xxx), its cleaner.

The general idea is fine already, just the code needs to be cleaner.

**Comment by trubitsyn** [comment]
I've also moved text handling to `handleText()` for a better readability.

**Comment by tibbi** [comment]
ye generally it looks ok, thanks. Ill just make some small tweaks to make it even simpler

**Comment by trubitsyn** [comment]
Thanks for help in implementing this. Don't forget to close #56

**Pull request merged**
